spring:
  datasource:
    url: jdbc:mariadb://localhost/service
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true